### ISSUE TITLE
[Bug]: Go to Top feature placement wrong

### ISSUE THREAD

**Issue by NK-Works** [VesperAkshay/qr-code-generator#275]
**Description**
The go to top button placement and size is not accurate

**To Reproduce**
1. Go to main page
2. Scroll down to.

**Expected behavior**
The button should appear next to the chatbot icon and it should be proper in size

**Screenshots**
![image](https://github.com/user-attachments/assets/668a5da0-fb1e-4e99-89b7-4b0a170b41a8)

I can fix it

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've made adjustments to the ScrollButton component to improve its placement and size. The button has been moved to the bottom right corner of the screen and its size has been reduced for a more subtle appearance. Additionally, I've added a transition effect for a smoother appearance and disappearance.

I also created pull request: https://github.com/VesperAkshay/qr-code-generator/pull/276


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by NK-Works** [comment]
@VesperAkshay what is this ai stuff coming here...
I mean wasn't gssoc meant for fledgling developers to learn about open source contributions... If even this is being done by ai then the gssoc will have no meaning at the end of the day... as 90% of the PRs generated in the gssoc are by fledgling devs and all of them can be directly done by ai...
so pls rather than taking the pr made by ai assign me
